// try{
//     a
// } catch(e) {
//     console.log('err' + e)
// }

try {
    a
} catch(e){
    console.log('a')
}